### ISSUE TITLE
About the dilation setting

### ISSUE THREAD

**Issue by SudongCAI** [theFoxofSky/ddfnet#22]
Hi author, thanks for your wonderful work. Today I noticed a problem in the dilation setting about the DDF model that "dilation" cannot set to 8 or more (like 16), otherwise the core will be dumped. I wonder how to solve this problem, even after checking the .cuda files... I will be very grateful if you can let me know how to solve this problem. Thank you very much.

**Comment by theFoxofSky** [comment]
I think this problem may be caused by the CUDA setting. 

I also meet a similar problem when using very big batch sizes (for example, 384 or more for one GPU). I temporarily fixed the batch size issue in my private ddf repo by modified Cuda filtes.

You may also need to modify the Cuda files if you want to use large dilation. 

BTW, if you use large dilation,  ddf will become very slow since the faster version cannot be used in large dilation setting.

**Comment by SudongCAI** [comment]
Thank you so much for the reply, that's very kind. By the way, may I have another question: as for the 'mul_faster', I looked into the 'cuda' file and it seems no backward function was defined there. Is this faster version only for forward inference and cannot be independently applied in the training phase?

**Comment by theFoxofSky** [comment]
No difference in the performance. I just optimized the forward part, I have not optimized the backward part yet. So the training will not be significantly faster. But the inference speed will be faster.

**Comment by SudongCAI** [comment]
Understood. Thank you so much.

**Comment by jlhou** [comment]
I would like to ask whether you have realized the code with larger "dilation" and could you share it with me.
